name: Build and Distribute Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Create Firebase credentials
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > "$RUNNER_TEMP/firebase-service-account.json"

      - name: Upload APK to Firebase App Distribution
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/firebase-service-account.json
        run: |
          npx firebase-tools appdistribution:distribute \
            build/app/outputs/flutter-apk/app-release.apk \
            --app "1:214438274387:android:87e6e013482ffed4072da6" \
            --release-notes "Automatic build from GitHub"